const services = [
  {
    id: 0,
    name: "All",
    description: "Classic haircut with a consultation.",
    price: 25.0,
    type: "Hair",
  },
  {
    id: 1,
    name: "Haircut",
    description: "Classic haircut with a consultation.",
    price: 25.0,
    type: "Hair",
  },
  {
    id: 2,
    name: "Coloring",
    description: "Full head coloring with premium products.",
    price: 75.0,
    type: "Hair",
  },
  {
    id: 3,
    name: "Manicure",
    description: "Nail shaping, cuticle care, and polish.",
    price: 20.0,
    type: "Nails",
  },
  {
    id: 4,
    name: "Pedicure",
    description: "Soothing foot soak, scrub, and polish.",
    price: 30.0,
    type: "Nails",
  },
  {
    id: 5,
    name: "Facial",
    description: "Deep cleansing facial for all skin types.",
    price: 50.0,
    type: "Skincare",
  },
  {
    id: 6,
    name: "Massage",
    description: "Relaxing full-body massage.",
    price: 80.0,
    type: "Spa",
  },
  {
    id: 7,
    name: "Waxing",
    description: "Full body waxing service.",
    price: 40.0,
    type: "Body",
  },
  {
    id: 8,
    name: "Threading",
    description: "Eyebrow shaping and facial threading.",
    price: 15.0,
    type: "Face",
  },
  {
    id: 9,
    name: "Makeup",
    description: "Professional makeup for any occasion.",
    price: 60.0,
    type: "Makeup",
  },
  {
    id: 10,
    name: "Bridal",
    description: "Comprehensive bridal beauty package.",
    price: 300.0,
    type: "Special",
  },
];

export default services;
