const shops = [
  {
    id: "1",
    name: "Elite Spa",
    rating: 4.5,
    distance: 2.3,
    location: "23 Green Valley, Sunset St, 560001",
  },
  {
    id: "2",
    name: "Glamour Salon",
    rating: 4.7,
    distance: 1.8,
    location: "12 Maple Street, Downtown, 560002",
  },
  {
    id: "3",
    name: "Urban Parlour",
    rating: 4.2,
    distance: 3.5,
    location: "89 Downtown Plaza, King Rd, 560003",
  },
  {
    id: "4",
    name: "Luxury Spa",
    rating: 4.8,
    distance: 0.9,
    location: "45 Ocean Drive, Beachside, 560004",
  },
  {
    id: "5",
    name: "Style & Shine Salon",
    rating: 4.3,
    distance: 2.1,
    location: "101 Cedar Park, Hill Rd, 560005",
  },
  {
    id: "6",
    name: "Blissful Spa",
    rating: 4.6,
    distance: 4.0,
    location: "55 Sunset Boulevard, Crescent Ave, 560006",
  },
  {
    id: "7",
    name: "Serenity Parlour",
    rating: 4.1,
    distance: 3.2,
    location: "11 Hilltop Avenue, Brook St, 560007",
  },
  {
    id: "8",
    name: "Chic Salon",
    rating: 4.9,
    distance: 1.2,
    location: "7 Rosewood Lane, Pine St, 560008",
  },
  {
    id: "9",
    name: "Harmony Spa",
    rating: 4.4,
    distance: 2.9,
    location: "33 Pine Grove, Maple Rd, 560009",
  },
  {
    id: "10",
    name: "Radiance Parlour",
    rating: 4.2,
    distance: 1.5,
    location: "90 Elm Street, Greenfield, 560010",
  },
  {
    id: "11",
    name: "Glow & Shine Salon",
    rating: 4.7,
    distance: 3.7,
    location: "66 Pearl Avenue, Oak St, 560011",
  },
  {
    id: "12",
    name: "Majestic Spa",
    rating: 4.0,
    distance: 5.0,
    location: "120 Highland Park, Royal Rd, 560012",
  },
  {
    id: "13",
    name: "Elegant Parlour",
    rating: 4.3,
    distance: 2.4,
    location: "78 Birchwood Road, Valley St, 560013",
  },
  {
    id: "14",
    name: "Luxe Salon",
    rating: 4.8,
    distance: 1.1,
    location: "5 Coral Street, Bridge Rd, 560014",
  },
  {
    id: "15",
    name: "Zen Spa",
    rating: 4.6,
    distance: 3.0,
    location: "87 Willow Creek, Lake Rd, 560015",
  },
  {
    id: "16",
    name: "Velvet Touch Parlour",
    rating: 4.5,
    distance: 2.6,
    location: "110 Maplewood Drive, Oakfield, 560016",
  },
  {
    id: "17",
    name: "Tranquility Spa",
    rating: 4.9,
    distance: 1.9,
    location: "99 Lakeshore Road, Forest St, 560017",
  },
  {
    id: "18",
    name: "Splendid Salon",
    rating: 4.1,
    distance: 3.3,
    location: "45 Magnolia Street, Elm St, 560018",
  },
  {
    id: "19",
    name: "Glow Beauty Parlour",
    rating: 4.4,
    distance: 2.7,
    location: "37 Aspen Heights, Mountain Rd, 560019",
  },
  {
    id: "20",
    name: "Rejuvenate Spa",
    rating: 4.7,
    distance: 1.4,
    location: "22 Oakwood Boulevard, Birch St, 560020",
  },
];

export default shops;
